Argument for repository
NicholasMoser/Six-Patches-Of-Pain pull request #3
Opened 2021-10-16 10:26 UTC by Athkore

Added argument parsing for repository, iso path, and a toggle to save the recently ran config to file, which would make arguments reduntant when using the same parameters the next time

2021-10-25 13:45 UTC, NicholasMoser commented on six_patches_of_pain.go
> +	if len(os.Args) == 2 {
Since the application didn't have args before, I could always presume that a second arg was the ISO. With the new flags I'm not sure that's the case anymore since you could just do one flag. I'll do some testing to check this.

2021-10-25 14:03 UTC, NicholasMoser commented on go.mod
> +	github.com/cheggaaa/pb/v3 v3.0.8
Was there a particular reason you upgraded this dependency, or was it just a "why not?" upgrade?

2021-10-25 14:05 UTC, NicholasMoser commented
Overall LGTM, I'll see about getting this tested, merged, and released this week.

2021-10-26 21:15 UTC, Athkore commented on go.mod
> +	github.com/cheggaaa/pb/v3 v3.0.8
that one I didn't notice, was 100% unintentional

2021-10-26 21:19 UTC, Athkore commented on six_patches_of_pain.go
> +	if len(os.Args) == 2 {
From what I can discern, a flag without an attached argument just shows the help message before exiting. Even if the flag is not registered.
Don't know if there is any way around it that would be easy to mistakenly do.

2021-11-10 05:03 UTC, NicholasMoser requested changes

2021-11-10 05:03 UTC, NicholasMoser commented on six_patches_of_pain.go
> +	print(isoPath)
Please remove this print statement.

2021-11-10 05:03 UTC, NicholasMoser commented on six_patches_of_pain.go
> +	flag.StringVar(&argGitRepository,"r",DefaultGitRepository,"Specify git repository to download updates from as 'https://api.github.com/repos/{user}/{repository}/releases'")
So if I run Six Patches of Pain once without flags, it will download from `NicholasMoser/SCON4-Releases`. If I run it again with `-r` pointing to a different repo, such as `Super-GNT4/SCON4-Betas`[1] it will fail as it tries to use the original repository. It will work however if I also pass in `-s`[2].

I believe this is because the logic occurs in the following order:

1. Call `verifyIntegrity()` and set the new git repository to the git repository file if `saveConfig` is true.
2. Call `downloadNewVersion()` and download the new release from the git repository.

If `saveConfig` is not true, the git repository will not be updated. I think I may prefer removing the `-s` flag entirely. Instead, just assume that you want to change the git repository for all future calls without `-s`. In other words, make `saveConfig` always true. Would make the code a lot simpler. Curious to hear what you think.

[1] `Six-Patches-Of-Pain.exe -r "https://api.github.com/repos/Super-GNT4/SCON4-Betas/releases"`
[2] `Six-Patches-Of-Pain.exe -r "https://api.github.com/repos/Super-GNT4/SCON4-Betas/releases" -s`

2022-03-09 10:38 UTC, Athkore commented on six_patches_of_pain.go
> +	flag.StringVar(&argGitRepository,"r",DefaultGitRepository,"Specify git repository to download updates from as 'https://api.github.com/repos/{user}/{repository}/releases'")
I kinda dropped the ball on this, completely forgot to check in.
Now the -s argument is removed, and it's assumed that the given settings should be saved.

2022-03-09 10:38 UTC, Athkore commented on six_patches_of_pain.go
> +	print(isoPath)
It is now removed

2022-04-13 01:16 UTC, NicholasMoser approved these changes

2022-04-13 01:16 UTC, merged